library(keras)
library(dplyr)
library(tidyr)
library(stringr)
library(survPen)
library(stringi)
library("corrplot")
getwd()

# install.packages("tfdatasets")
library(tfdatasets)
dataset<-dataset_boston_housing()
View(dataset$train)
View(dataset$test)
c(c(train_data, train_targets), c(test_data, test_targets)) %<-% dataset
# str(train_data)
# str(test_data)
# str(train_targets)
# str(test_targets)
View(train_data)
View(test_data)
View(train_targets)
View(test_targets)
